version: '3.7'

services:
  my_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./.env.prod

  my_redis:
    image: redis:latest
    ports:
      - 6379:6379
